name: Convert Scripts

on:
  push:
    branches: [ main ]
    paths:
      - 'QuantumultX/*.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'QuantumultX/*.js'
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Clone Script Hub repository
        run: |
          git clone https://github.com/Script-Hub-Org/Script-Hub.git
          cd Script-Hub
          npm install
          
      - name: Create output directories
        run: |
          mkdir -p Surge
          mkdir -p Loon
      
      - name: Convert QuantumultX scripts to Surge
        run: |
          for file in QuantumultX/*.js; do
            filename=$(basename "$file")
            echo "Converting $filename to Surge format..."
            node Script-Hub/scripts/convert.js --input "$file" --output "Surge/${filename}" --target surge
          done
      
      - name: Convert QuantumultX scripts to Loon
        run: |
          for file in QuantumultX/*.js; do
            filename=$(basename "$file")
            echo "Converting $filename to Loon format..."
            node Script-Hub/scripts/convert.js --input "$file" --output "Loon/${filename}" --target loon
          done
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Surge/ Loon/
          git commit -m "Auto convert scripts to Surge and Loon formats" || echo "No changes to commit"
          git push
