name: Convert QuantumultX Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the conversion script
      - name: Run conversion
        run: npm run convert

      # Commit and push converted files
      - name: Commit converted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Surge/* Loon/*
          git commit -m "Add converted scripts for Surge and Loon" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
