name: Metadata-Aware Extractor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-and-convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directories
        run: mkdir -p Surge Loon
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Create metadata-aware Python extractor script
        run: |
          cat > extract_metadata.py << 'EOF'
          import os
          import re
          import sys
          
          def extract_info(file_path):
              try:
                  with open(file_path, 'r', encoding='utf-8') as file:
                      content = file.read()
                  
                  # Get filename without extension
                  filename = os.path.basename(file_path).replace('.js', '')
                  
                  # Extract script name (line after 📜)
                  script_name = filename
                  name_match = re.search(r'📜\s*(.*?)[\n\r]', content, re.DOTALL)
                  if name_match:
                      script_name = name_match.group(1).strip()
                  
                  # Extract metadata directly from source
                  desc = "媒体制作 - 模块"
                  desc_match = re.search(r'#!desc\s*=\s*(.*?)[\n\r]', content)
                  if desc_match:
                      desc = desc_match.group(1).strip()
                  
                  category = "🔐APP"
                  category_match = re.search(r'#!category\s*=\s*(.*?)[\n\r]', content)
                  if category_match:
                      category = category_match.group(1).strip()
                  
                  author = "🅜ⓘ🅚ⓔ🅟ⓗ🅘ⓔ"
                  author_match = re.search(r'#!author\s*=\s*(.*?)[\n\r]', content)
                  if author_match:
                      author = author_match.group(1).strip()
                  
                  # Extract URL pattern for script-response-body
                  url_pattern = "^https?://example.com/"
                  
                  # Find script-response-body block
                  rewrite_section = re.search(r'\[rewrite_local\](.*?)(\[|$)', content, re.DOTALL | re.IGNORECASE)
                  if rewrite_section:
                      section_content = rewrite_section.group(1)
                      
                      # Find script-response-body line
                      response_pattern_match = re.search(r'^([^\s]+)\s+url\s+script-response-body', section_content, re.MULTILINE)
                      if response_pattern_match:
                          url_pattern = response_pattern_match.group(1).strip()
                  
                  # Extract original script path
                  script_path = f"{filename}.js"
                  script_path_match = re.search(r'script-response-body\s+(https?:\/\/[^\s\n]+)', content)
                  if script_path_match:
                      full_path = script_path_match.group(1).strip()
                      script_path = os.path.basename(full_path)
                  
                  # Extract hostname
                  hostname = "example.com"
                  hostname_match = re.search(r'hostname\s*=\s*(.*?)[\n\r]', content)
                  if hostname_match:
                      hostname = hostname_match.group(1).strip()
                  
                  # Extract reject rules
                  reject_rules = []
                  if rewrite_section:
                      section_content = rewrite_section.group(1)
                      for line in section_content.split('\n'):
                          if 'reject' in line and not 'script' in line:
                              parts = line.strip().split()
                              if len(parts) >= 2 and parts[0] and 'reject' in line:
                                  reject_rules.append(parts[0])
                  
                  return {
                      'filename': filename,
                      'script_name': script_name,
                      'desc': desc,
                      'category': category,
                      'author': author,
                      'url_pattern': url_pattern,
                      'hostname': hostname,
                      'script_path': script_path,
                      'reject_rules': reject_rules
                  }
              except Exception as e:
                  print(f"Error processing {file_path}: {str(e)}", file=sys.stderr)
                  return {
                      'filename': os.path.basename(file_path).replace('.js', ''),
                      'script_name': os.path.basename(file_path).replace('.js', ''),
                      'desc': "媒体制作 - 模块",
                      'category': "🔐APP",
                      'author': "🅜ⓘ🅚ⓔ🅟ⓗ🅘ⓔ",
                      'url_pattern': "^https?://example.com/",
                      'hostname': "example.com",
                      'script_path': os.path.basename(file_path),
                      'reject_rules': []
                  }
          
          def create_loon_template(info):
              # For Loon, modify the description
              loon_desc = info['desc'].replace("模块", "插件") if "模块" in info['desc'] else info['desc']
              
              template = f"""#!name = {info['script_name']}🔐APP解锁
          #!desc = {loon_desc}
          #!author = {info['author']}
          #!icon = https://raw.githubusercontent.com/Mikephie/icons/main/icon/{info['filename']}.png
          """
              
              # Add reject rules if any
              if info['reject_rules']:
                  template += "\n[Rewrite]"
                  for rule in info['reject_rules']:
                      template += f"\n{rule} reject"
                  template += "\n"
              
              # Add Script section
              template += f"\n[Script]\nhttp-response {info['url_pattern']} script-path=https://raw.githubusercontent.com/Mikephie/Script/main/qx/{info['script_path']}, requires-body=true, timeout=60, tag={info['filename']}"
              
              # Add MITM section
              template += f"\n\n[MITM]\nhostname = {info['hostname']}"
              
              return template
          
          def create_surge_template(info):
              template = f"""#!name = {info['script_name']}🔐APP
          #!desc = {info['desc']}
          #!author = {info['author']}
          #!category={info['category']}
          """
              
              # Add reject rules if any
              if info['reject_rules']:
                  template += "\n[URL Rewrite]"
                  for rule in info['reject_rules']:
                      template += f"\n{rule} - reject"
                  template += "\n"
              
              # Add Script section
              template += f"\n[Script]\n{info['filename']} = type=http-response, pattern={info['url_pattern']}, script-path=https://raw.githubusercontent.com/Mikephie/Script/main/qx/{info['script_path']}, requires-body=true, max-size=-1, timeout=60"
              
              # Add MITM section
              template += f"\n\n[MITM]\nhostname = %APPEND% {info['hostname']}"
              
              return template
          
          def main():
              if len(sys.argv) < 2:
                  print("Usage: python extract_metadata.py <qx_script_file>")
                  sys.exit(1)
              
              file_path = sys.argv[1]
              info = extract_info(file_path)
              
              # Print info for debugging
              print(f"Extracted info for {info['filename']}:")
              print(f"  Script name: {info['script_name']}")
              print(f"  Description: {info['desc']}")
              print(f"  Category: {info['category']}")
              print(f"  Author: {info['author']}")
              print(f"  URL pattern: {info['url_pattern']}")
              print(f"  Script path: {info['script_path']}")
              print(f"  Hostname: {info['hostname']}")
              print(f"  Reject rules: {', '.join(info['reject_rules']) if info['reject_rules'] else 'None'}")
              
              # Create templates
              loon_content = create_loon_template(info)
              surge_content = create_surge_template(info)
              
              # Write to files
              loon_path = f"Loon/{info['filename']}.plugin"
              surge_path = f"Surge/{info['filename']}.sgmodule"
              
              with open(loon_path, 'w', encoding='utf-8') as file:
                  file.write(loon_content)
              
              with open(surge_path, 'w', encoding='utf-8') as file:
                  file.write(surge_content)
              
              print(f"Created templates: {loon_path} and {surge_path}")
          
          if __name__ == "__main__":
              main()
          EOF
      
      - name: Process scripts
        run: |
          # Process each file with metadata-aware Python script
          for file in QuantumultX/*.js; do
            echo "Processing $file..."
            python extract_metadata.py "$file"
          done
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Surge/ Loon/
          git commit -m "Add metadata-aware templates preserving original values" || echo "No changes to commit"
          git push || echo "Nothing to push"
