name: Node.js File Creator

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directories
        run: mkdir -p Surge Loon
      
      - name: Create template files
        run: node -e "
          const fs = require('fs');
          const path = require('path');
          
          try {
            // Get all JS files in QuantumultX directory
            const qxDir = path.join(process.cwd(), 'QuantumultX');
            const files = fs.readdirSync(qxDir).filter(file => file.endsWith('.js'));
            
            files.forEach(file => {
              const filename = path.basename(file, '.js');
              console.log('Creating templates for ' + filename + '...');
              
              // Create Loon plugin
              const loonContent = '#!name = ' + filename + '🔐APP解锁\n' +
                '#!desc = 媒体制作 - 插件\n' +
                '#!author = 🅜ⓘ🅚ⓔ🅟ⓗ🅘ⓔ\n' +
                '#!icon = https://raw.githubusercontent.com/Mikephie/icons/main/icon/' + filename + '.png\n\n' +
                '[Script]\n' +
                'http-response ^https?://example.com/ script-path=https://raw.githubusercontent.com/Mikephie/Script/main/qx/' + filename + '.js, requires-body=true, timeout=60, tag=' + filename + '\n\n' +
                '[MITM]\n' +
                'hostname = example.com';
              
              // Create Surge module
              const surgeContent = '#!name = ' + filename + '🔐APP\n' +
                '#!desc = 媒体制作 - 模块\n' +
                '#!author = 🅜ⓘ🅚ⓔ🅟ⓗ🅘ⓔ\n' +
                '#!category=🔐APP\n\n' +
                '[Script]\n' +
                filename + ' = type=http-response, pattern=^https?://example.com/, script-path=https://raw.githubusercontent.com/Mikephie/Script/main/qx/' + filename + '.js, requires-body=true, max-size=-1, timeout=60\n\n' +
                '[MITM]\n' +
                'hostname = %APPEND% example.com';
              
              // Write the files
              fs.writeFileSync(path.join(process.cwd(), 'Loon', filename + '.plugin'), loonContent);
              fs.writeFileSync(path.join(process.cwd(), 'Surge', filename + '.sgmodule'), surgeContent);
            });
          } catch (error) {
            console.error('Error:', error);
            process.exit(1);
          }
        "
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Surge/ Loon/
          git commit -m "Created template files" || echo "No changes to commit"
          git push || echo "Nothing to push"
